# Generated by Django 3.1.4 on 2021-05-06 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
