# Generated by Django 3.1.4 on 2021-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20210507_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
