# Generated by Django 3.1.4 on 2021-05-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iban',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(max_length=250),
        ),
    ]
